version: '3.7'

services:
        django_gunicorn:
                volumes:
                        - static:/static
                env_file:
                        - .env
                build:
                        context: .
        nginx:
                build: ./nginx
                volumes:
                        - static:/static
                depends_on:
                        - django_gunicorn               

volumes:
        static:
